oncrpc: bind service to localhost during unit testing.
Motivation:

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)

Acked-by: Paul Millar
Target: master, 3.0
(cherry picked from commit d7f934b4b9e26524c4dabc08dbdf8e5c1fd58f0f)
Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>